### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by senlin-ali** [Rapternmn/PyTorch-Onnx-Tensorrt#13]
Layer of type maxpool not supported, skipping ONNX node generation.
Layer of type maxpool not supported, skipping ONNX node generation.
Layer of type maxpool not supported, skipping ONNX node generation.
Layer of type yolo not supported, skipping ONNX node generation.
Layer of type yolo not supported, skipping ONNX node generation.
Layer of type yolo not supported, skipping ONNX node generation.
Traceback (most recent call last):
  File "create_onnx.py", line 772, in <module>
    main()
  File "create_onnx.py", line 760, in main
    verbose=True)
  File "create_onnx.py", line 392, in build_onnx_graph
    params)
  File "create_onnx.py", line 269, in load_conv_weights
    conv_params, 'conv', 'weights')
  File "create_onnx.py", line 298, in _create_param_tensors
    conv_params, param_category, suffix)
  File "create_onnx.py", line 328, in _load_one_param_type
    buffer=self.weights_file.read(param_size * 4))
TypeError: buffer is too small for requested array

**Comment by Rapternmn** [comment]
Hii, what is the onnx version?

**Comment by senlin-ali** [comment]
> Hii, what is the onnx version?

hi 1.7.0

**Comment by senlin-ali** [comment]
hi there is another problem  ,my weight is '.pt',not .weight ; is this ok?

**Comment by Rapternmn** [comment]
Please follow the README Instructions for getting it up and running
Onnx 1.4.1
