### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by 17702513221** [Rapternmn/PyTorch-Onnx-Tensorrt#8]
when i use yolov3.cfg and yolov3.weights in python3 create_onnx.py --reso 416 ,i get a error:
Traceback (most recent call last):
  File "create_onnx.py", line 772, in <module>
    main()
  File "create_onnx.py", line 740, in main
    layer_configs = parser.parse_cfg_file(cfg_file_path)
  File "create_onnx.py", line 45, in parse_cfg_file
    layer_dict, layer_name, remainder = self._next_layer(remainder)
  File "create_onnx.py", line 86, in _next_layer
    layer_param_block, remainder = remainder.split('\n\n', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dfomin** [comment]
Put the new line at the end of the yolov3.cfg

**Comment by Siraj-Qazi** [comment]
> Put the new line at the end of the yolov3.cfg

Lol
